baseURL = "https://angular-austria.at/"
languageCode = "en-us"
title = "Angular Austria Association"

[[menu.main]]
	name = "Videos"
	url = "/videos/"
    weight = 1

[[menu.main]]
    name = "Jobs"
    url = "/jobs/"
    weight = 2