/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MeetupEvent,
} from './components/app-meetup-event/app-meetup-event';

export namespace Components {
  interface App404 {}
  interface AppContact {}
  interface AppEvents {}
  interface AppFooter {}
  interface AppHeaderNav {}
  interface AppHome {}
  interface AppImprint {}
  interface AppJobs {}
  interface AppMeetupEvent {
    'eventData': MeetupEvent;
  }
  interface AppMeetupWidget {
    'displayOrder': boolean;
    'groupName': string;
    'pageCount': string;
    'queryParams': string;
    'textFormat': string;
  }
  interface AppPrivacy {}
  interface AppProjects {}
  interface AppRoot {}
  interface AppSlackinfo {}
  interface AppTeam {}
  interface AppTraining {}
  interface AppVideos {}
}

declare global {


  interface HTMLApp404Element extends Components.App404, HTMLStencilElement {}
  var HTMLApp404Element: {
    prototype: HTMLApp404Element;
    new (): HTMLApp404Element;
  };

  interface HTMLAppContactElement extends Components.AppContact, HTMLStencilElement {}
  var HTMLAppContactElement: {
    prototype: HTMLAppContactElement;
    new (): HTMLAppContactElement;
  };

  interface HTMLAppEventsElement extends Components.AppEvents, HTMLStencilElement {}
  var HTMLAppEventsElement: {
    prototype: HTMLAppEventsElement;
    new (): HTMLAppEventsElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHeaderNavElement extends Components.AppHeaderNav, HTMLStencilElement {}
  var HTMLAppHeaderNavElement: {
    prototype: HTMLAppHeaderNavElement;
    new (): HTMLAppHeaderNavElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppImprintElement extends Components.AppImprint, HTMLStencilElement {}
  var HTMLAppImprintElement: {
    prototype: HTMLAppImprintElement;
    new (): HTMLAppImprintElement;
  };

  interface HTMLAppJobsElement extends Components.AppJobs, HTMLStencilElement {}
  var HTMLAppJobsElement: {
    prototype: HTMLAppJobsElement;
    new (): HTMLAppJobsElement;
  };

  interface HTMLAppMeetupEventElement extends Components.AppMeetupEvent, HTMLStencilElement {}
  var HTMLAppMeetupEventElement: {
    prototype: HTMLAppMeetupEventElement;
    new (): HTMLAppMeetupEventElement;
  };

  interface HTMLAppMeetupWidgetElement extends Components.AppMeetupWidget, HTMLStencilElement {}
  var HTMLAppMeetupWidgetElement: {
    prototype: HTMLAppMeetupWidgetElement;
    new (): HTMLAppMeetupWidgetElement;
  };

  interface HTMLAppPrivacyElement extends Components.AppPrivacy, HTMLStencilElement {}
  var HTMLAppPrivacyElement: {
    prototype: HTMLAppPrivacyElement;
    new (): HTMLAppPrivacyElement;
  };

  interface HTMLAppProjectsElement extends Components.AppProjects, HTMLStencilElement {}
  var HTMLAppProjectsElement: {
    prototype: HTMLAppProjectsElement;
    new (): HTMLAppProjectsElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSlackinfoElement extends Components.AppSlackinfo, HTMLStencilElement {}
  var HTMLAppSlackinfoElement: {
    prototype: HTMLAppSlackinfoElement;
    new (): HTMLAppSlackinfoElement;
  };

  interface HTMLAppTeamElement extends Components.AppTeam, HTMLStencilElement {}
  var HTMLAppTeamElement: {
    prototype: HTMLAppTeamElement;
    new (): HTMLAppTeamElement;
  };

  interface HTMLAppTrainingElement extends Components.AppTraining, HTMLStencilElement {}
  var HTMLAppTrainingElement: {
    prototype: HTMLAppTrainingElement;
    new (): HTMLAppTrainingElement;
  };

  interface HTMLAppVideosElement extends Components.AppVideos, HTMLStencilElement {}
  var HTMLAppVideosElement: {
    prototype: HTMLAppVideosElement;
    new (): HTMLAppVideosElement;
  };
  interface HTMLElementTagNameMap {
    'app-404': HTMLApp404Element;
    'app-contact': HTMLAppContactElement;
    'app-events': HTMLAppEventsElement;
    'app-footer': HTMLAppFooterElement;
    'app-header-nav': HTMLAppHeaderNavElement;
    'app-home': HTMLAppHomeElement;
    'app-imprint': HTMLAppImprintElement;
    'app-jobs': HTMLAppJobsElement;
    'app-meetup-event': HTMLAppMeetupEventElement;
    'app-meetup-widget': HTMLAppMeetupWidgetElement;
    'app-privacy': HTMLAppPrivacyElement;
    'app-projects': HTMLAppProjectsElement;
    'app-root': HTMLAppRootElement;
    'app-slackinfo': HTMLAppSlackinfoElement;
    'app-team': HTMLAppTeamElement;
    'app-training': HTMLAppTrainingElement;
    'app-videos': HTMLAppVideosElement;
  }
}

declare namespace LocalJSX {
  interface App404 extends JSXBase.HTMLAttributes<HTMLApp404Element> {}
  interface AppContact extends JSXBase.HTMLAttributes<HTMLAppContactElement> {}
  interface AppEvents extends JSXBase.HTMLAttributes<HTMLAppEventsElement> {}
  interface AppFooter extends JSXBase.HTMLAttributes<HTMLAppFooterElement> {}
  interface AppHeaderNav extends JSXBase.HTMLAttributes<HTMLAppHeaderNavElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppImprint extends JSXBase.HTMLAttributes<HTMLAppImprintElement> {}
  interface AppJobs extends JSXBase.HTMLAttributes<HTMLAppJobsElement> {}
  interface AppMeetupEvent extends JSXBase.HTMLAttributes<HTMLAppMeetupEventElement> {
    'eventData'?: MeetupEvent;
  }
  interface AppMeetupWidget extends JSXBase.HTMLAttributes<HTMLAppMeetupWidgetElement> {
    'displayOrder'?: boolean;
    'groupName'?: string;
    'pageCount'?: string;
    'queryParams'?: string;
    'textFormat'?: string;
  }
  interface AppPrivacy extends JSXBase.HTMLAttributes<HTMLAppPrivacyElement> {}
  interface AppProjects extends JSXBase.HTMLAttributes<HTMLAppProjectsElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppSlackinfo extends JSXBase.HTMLAttributes<HTMLAppSlackinfoElement> {}
  interface AppTeam extends JSXBase.HTMLAttributes<HTMLAppTeamElement> {}
  interface AppTraining extends JSXBase.HTMLAttributes<HTMLAppTrainingElement> {}
  interface AppVideos extends JSXBase.HTMLAttributes<HTMLAppVideosElement> {}

  interface IntrinsicElements {
    'app-404': App404;
    'app-contact': AppContact;
    'app-events': AppEvents;
    'app-footer': AppFooter;
    'app-header-nav': AppHeaderNav;
    'app-home': AppHome;
    'app-imprint': AppImprint;
    'app-jobs': AppJobs;
    'app-meetup-event': AppMeetupEvent;
    'app-meetup-widget': AppMeetupWidget;
    'app-privacy': AppPrivacy;
    'app-projects': AppProjects;
    'app-root': AppRoot;
    'app-slackinfo': AppSlackinfo;
    'app-team': AppTeam;
    'app-training': AppTraining;
    'app-videos': AppVideos;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


